---
- hosts: dev
  become: true
  tasks:
  - name: install python pip
    yum:
      name: python-pip
      state: present
  - name: install docker
    yum:
      name: docker
      state: present
  - name: start docker
    service:
      name: docker
      state: started
  - name: inatall docker-py python module
    pip:
      name: docker-py
      state: present
  - name: stop the conatiner
      shell: docker stop mycontainer
  - name: remove container
      shell: docker rm mycontainer
  - name: remove image
      shell: docker image rmi techguftgu22231/image:0.01    
  - name: start the container
    docker_container:
      name: mycontainer
      image: techguftgu22231/image:0.01
      state: started
      published_ports:
          - 0.0.0.0:8080:8080
    
  
